CREATE TABLE public.airp_airplane
(
    airp_sq_airplane   int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    airp_tx_codigo     varchar NOT NULL,
    airp_tx_modelo     varchar NOT NULL,
    airp_qt_passageiro int4    NOT NULL,
    airp_dt_registro   varchar NOT NULL,
    CONSTRAINT airp_airplane_pkey PRIMARY KEY (airp_sq_airplane)
);

CREATE UNIQUE INDEX ix_un_airp_tx_codigo ON public.airp_airplane USING btree (airp_tx_codigo);

CREATE TABLE public.busi_bus_line
(
    busi_sq_bus_line int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    busi_tx_code     varchar NOT NULL,
    busi_tx_name     varchar NOT NULL,
    CONSTRAINT busi_bus_line_pkey PRIMARY KEY (busi_sq_bus_line)
);

CREATE TABLE public.itne_itinerary
(
    itne_sq_itinerary int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    busi_sq_bus_line  int4    NOT NULL,
    itne_tx_name      varchar NOT NULL,
    itne_tx_code      varchar NOT NULL,
    CONSTRAINT itne_itinerary_pkey PRIMARY KEY (itne_sq_itinerary)
);

ALTER TABLE public.itne_itinerary
    ADD CONSTRAINT fk_busi_itne FOREIGN KEY (busi_sq_bus_line) REFERENCES public.busi_bus_line (busi_sq_bus_line);

CREATE TABLE public.cord_coordinate
(
    cord_sq_coordinate int4             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    itne_sq_itinerary  int4             NOT NULL,
    cord_dp_longitude  DOUBLE PRECISION NOT NULL,
    cord_dp_latitude   DOUBLE PRECISION NOT NULL,
    CONSTRAINT cord_coordinate_pkey PRIMARY KEY (cord_sq_coordinate)
);


ALTER TABLE public.cord_coordinate
    ADD CONSTRAINT fk_itne_cord FOREIGN KEY (itne_sq_itinerary) REFERENCES public.itne_itinerary (itne_sq_itinerary);

